Repository hashicorp/vault-guides, pull requests merged in 2020-07, with the labels that each got.

#263 [Vault 1.5] Raft ha_storage support
  operations/raft-ha-storage/README.md
  operations/raft-ha-storage/existing_server/README.md
  operations/raft-ha-storage/existing_server/cluster.sh
  operations/raft-ha-storage/new_cluster/README.md
  operations/raft-ha-storage/new_cluster/cluster.sh
Labels: Learn, WIP

#271 Adds the AWS scenario for password policies
  secrets/password-policies/aws/README.md
  secrets/password-policies/aws/iam.tf
  secrets/password-policies/aws/main.tf
  secrets/password-policies/aws/network.tf
  secrets/password-policies/aws/outputs.tf
  secrets/password-policies/aws/security-groups.tf
  secrets/password-policies/aws/templates/userdata-vault-server.tpl
  secrets/password-policies/aws/terraform.tfvars.example
  secrets/password-policies/aws/variables.tf
  secrets/password-policies/aws/version.tf
Labels: WIP

#270 [Learn] Codify Vault Management tutorial assets
  operations/codify-mgmt/README.md
  operations/codify-mgmt/enterprise/auth.tf
  operations/codify-mgmt/enterprise/main.tf
  operations/codify-mgmt/enterprise/policies.tf
  operations/codify-mgmt/enterprise/policies/admin-policy.hcl
  operations/codify-mgmt/enterprise/policies/fpe-client-policy.hcl
  operations/codify-mgmt/enterprise/secrets.tf
  operations/codify-mgmt/oss/auth.tf
  operations/codify-mgmt/oss/main.tf
  operations/codify-mgmt/oss/policies.tf
  operations/codify-mgmt/oss/policies/admin-policy.hcl
  operations/codify-mgmt/oss/policies/eaas-client-policy.hcl
  operations/codify-mgmt/oss/secrets.tf
Labels: Learn, WIP

#275 Update the learn tutorial links
  operations/codify-mgmt/README.md
Labels: Learn

#278 [Lean] Azure auto-unseal update
  operations/azure-keyvault-unseal/README.md
  operations/azure-keyvault-unseal/main.tf
  operations/azure-keyvault-unseal/variables.tf
Labels: Learn
